### ISSUE TITLE
Home directory expansion not working

### ISSUE THREAD

**Issue by sciamp** [Suckttle/suckttle#1]
When running suckttle with no arguments we got:

```
     Running `target/debug/suckttle`
thread 'main' panicked at 'Unable to open the file: Error { repr: Os { code: 2, message: "No such file or directory" } }', /checkout/src/libcore/result.rs:916:5
```

This happens because shell expansion happens inside the shell before running the code, hence having 

```
const DEFAULT_CONF_PATH: &str = "~/.shuttle.json";
```

is not good because ~ won't expand to the user;s home directory.

I would suggest to use something like std::env::home_dir [0] to build the config file default path.

What you think @zarelit ?

[0] https://doc.rust-lang.org/1.10.0/std/env/fn.home_dir.html

**Comment by zarelit** [comment]
Agreed!
